#!/bin/bash

# Test script for cursor insertion functionality
echo "Testing Cursor Insertion & Editing"
echo "==================================="
echo ""
echo "Test Case 1: Middle Insertion"
echo "-----------------------------"
echo "1. Type: abcde"
echo "2. Press Left Arrow 2 times (cursor at 'd')"
echo "3. Type: xx"
echo "Expected: abcxxde"
echo ""
echo "Test Case 2: Chinese Character Insertion"
echo "-----------------------------------------"
echo "1. Type: 你好世界"
echo "2. Press Left Arrow 2 times (cursor at '世')"
echo "3. Type: 中文"
echo "Expected: 你好中文世界"
echo ""
echo "Test Case 3: Mixed Text Editing"
echo "--------------------------------"
echo "1. Type: Hello世界"
echo "2. Press Left Arrow 2 times (cursor at '世')"
echo "3. Type: 中文"
echo "4. Press Backspace once"
echo "Expected: Hello中世界"
echo ""
echo "Test Case 4: Delete Key"
echo "------------------------"
echo "1. Type: abcde"
echo "2. Press Home key (cursor at start)"
echo "3. Press Delete 2 times"
echo "Expected: cde"
echo ""
echo "Starting game..."
echo ""

dotnet run --project src/JinPingMei.Game